# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendar.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(801, 407)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(0, -10, 821, 431))
        self.textBrowser.setLineWidth(0)
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 351, 231))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 20, 331, 201))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setSelectedDate(QtCore.QDate(2017, 5, 30))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 10, 431, 231))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(130, 180, 271, 21))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setGeometry(QtCore.QRect(20, 120, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setGeometry(QtCore.QRect(300, 120, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 391, 81))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAcceptDrops(True)
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setDragEnabled(False)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setClearButtonEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit_3)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAcceptDrops(True)
        self.lineEdit_4.setAutoFillBackground(False)
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setDragEnabled(False)
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setClearButtonEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lineEdit_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAcceptDrops(True)
        self.lineEdit_5.setAutoFillBackground(False)
        self.lineEdit_5.setFrame(False)
        self.lineEdit_5.setDragEnabled(False)
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setClearButtonEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lineEdit_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 180, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setAcceptDrops(True)
        self.lineEdit_9.setAutoFillBackground(False)
        self.lineEdit_9.setFrame(False)
        self.lineEdit_9.setDragEnabled(False)
        self.lineEdit_9.setReadOnly(False)
        self.lineEdit_9.setClearButtonEnabled(False)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_5.setGeometry(QtCore.QRect(130, 150, 271, 21))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 150, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setAcceptDrops(True)
        self.lineEdit_8.setAutoFillBackground(False)
        self.lineEdit_8.setFrame(False)
        self.lineEdit_8.setDragEnabled(False)
        self.lineEdit_8.setReadOnly(False)
        self.lineEdit_8.setClearButtonEnabled(False)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 250, 351, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 321, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dateEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dateEdit.setWrapping(False)
        self.dateEdit.setFrame(True)
        self.dateEdit.setAccelerated(False)
        self.dateEdit.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dateEdit.setKeyboardTracking(True)
        self.dateEdit.setProperty("showGroupSeparator", False)
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.line_11 = QtWidgets.QFrame(self.layoutWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_11)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setAcceptDrops(True)
        self.lineEdit_11.setAutoFillBackground(False)
        self.lineEdit_11.setFrame(False)
        self.lineEdit_11.setDragEnabled(False)
        self.lineEdit_11.setReadOnly(False)
        self.lineEdit_11.setClearButtonEnabled(False)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lineEdit_11)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dateEdit_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dateEdit_2.setWrapping(False)
        self.dateEdit_2.setFrame(True)
        self.dateEdit_2.setAccelerated(False)
        self.dateEdit_2.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dateEdit_2.setKeyboardTracking(True)
        self.dateEdit_2.setProperty("showGroupSeparator", False)
        self.dateEdit_2.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit_2)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setAcceptDrops(True)
        self.lineEdit_12.setAutoFillBackground(False)
        self.lineEdit_12.setFrame(False)
        self.lineEdit_12.setDragEnabled(False)
        self.lineEdit_12.setReadOnly(False)
        self.lineEdit_12.setClearButtonEnabled(False)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lineEdit_12)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dateEdit_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dateEdit_3.setWrapping(False)
        self.dateEdit_3.setFrame(True)
        self.dateEdit_3.setAccelerated(False)
        self.dateEdit_3.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dateEdit_3.setKeyboardTracking(True)
        self.dateEdit_3.setProperty("showGroupSeparator", False)
        self.dateEdit_3.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dateEdit_3)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setAcceptDrops(True)
        self.lineEdit_10.setAutoFillBackground(False)
        self.lineEdit_10.setFrame(False)
        self.lineEdit_10.setDragEnabled(False)
        self.lineEdit_10.setReadOnly(False)
        self.lineEdit_10.setClearButtonEnabled(False)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit_10)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(370, 250, 421, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 391, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setAcceptDrops(True)
        self.lineEdit_13.setAutoFillBackground(False)
        self.lineEdit_13.setFrame(False)
        self.lineEdit_13.setDragEnabled(False)
        self.lineEdit_13.setReadOnly(False)
        self.lineEdit_13.setClearButtonEnabled(False)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit_13)
        self.comboBox_6 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setAcceptDrops(True)
        self.lineEdit_14.setAutoFillBackground(False)
        self.lineEdit_14.setFrame(False)
        self.lineEdit_14.setDragEnabled(False)
        self.lineEdit_14.setReadOnly(False)
        self.lineEdit_14.setClearButtonEnabled(False)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lineEdit_14)
        self.comboBox_7 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setAcceptDrops(True)
        self.lineEdit_15.setAutoFillBackground(False)
        self.lineEdit_15.setFrame(False)
        self.lineEdit_15.setDragEnabled(False)
        self.lineEdit_15.setReadOnly(False)
        self.lineEdit_15.setClearButtonEnabled(False)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lineEdit_15)
        self.comboBox_8 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 110, 120, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_4.setGeometry(QtCore.QRect(310, 110, 250, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setChecked(False)
        self.checkBox_4.setTristate(False)
        self.checkBox_4.setObjectName("checkBox_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Preview"))
        self.groupBox_2.setTitle(_translate("Dialog", "General Options"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "Single Selection"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "No Selection"))
        self.checkBox.setText(_translate("Dialog", "Grid"))
        self.checkBox_2.setText(_translate("Dialog", "Navigation Bar"))
        self.lineEdit_3.setText(_translate("Dialog", "Locale"))
        self.comboBox.setItemText(0, _translate("Dialog", "German/Germany"))
        self.comboBox.setItemText(1, _translate("Dialog", "Indonesian"))
        self.comboBox.setItemText(2, _translate("Dialog", "English"))
        self.comboBox.setItemText(3, _translate("Dialog", "Malaysian"))
        self.lineEdit_4.setText(_translate("Dialog", "Week starts on"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Sunday"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Monday"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Saturday"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "None"))
        self.lineEdit_5.setText(_translate("Dialog", "Selection mode"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Single Selection"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "No Selection"))
        self.lineEdit_9.setText(_translate("Dialog", "Vertical header"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "Short day names"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "Monday"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "Saturday"))
        self.comboBox_5.setItemText(3, _translate("Dialog", "None"))
        self.lineEdit_8.setText(_translate("Dialog", "Horizontal header"))
        self.groupBox_3.setTitle(_translate("Dialog", "Preview"))
        self.lineEdit_11.setText(_translate("Dialog", "Current  Date"))
        self.lineEdit_12.setText(_translate("Dialog", "Maximum Date"))
        self.lineEdit_10.setText(_translate("Dialog", "Minimum Date"))
        self.groupBox_4.setTitle(_translate("Dialog", "Preview"))
        self.lineEdit_13.setText(_translate("Dialog", "Weekday color"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "Black"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "Red"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "Blue"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "Grey"))
        self.lineEdit_14.setText(_translate("Dialog", "Weekend color"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "Black"))
        self.comboBox_7.setItemText(1, _translate("Dialog", "Red"))
        self.comboBox_7.setItemText(2, _translate("Dialog", "Blue"))
        self.comboBox_7.setItemText(3, _translate("Dialog", "Grey"))
        self.lineEdit_15.setText(_translate("Dialog", "Header text"))
        self.comboBox_8.setItemText(0, _translate("Dialog", "Bold"))
        self.comboBox_8.setItemText(1, _translate("Dialog", "Italic"))
        self.comboBox_8.setItemText(2, _translate("Dialog", "Standard"))
        self.checkBox_3.setText(_translate("Dialog", "First Friday in Blue"))
        self.checkBox_4.setText(_translate("Dialog", "May 1 in  red"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

