# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from detail_produk import*

class menufix(object):
    def setupUi(self, MainWindow):
        self.MENU = MainWindow
        MainWindow.setObjectName("MENU")
        MainWindow.resize(802, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        

        # Membuat label untuk ucapan selamat datang pada halaman menu
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 20, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        # Membuat scroll
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 80, 801, 731))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContents = QtWidgets.QWidget()
        self.scrollContents.setGeometry(QtCore.QRect(0, 0, 801, 731))
        self.scrollContents.setObjectName("scrollContents")

        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 0, 761, 711))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")

        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setKerning(True)
        self.frame.setFont(font)
        self.frame.setMouseTracking(True)
        self.frame.setTabletTracking(True)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")

        # Menampung frame dan label untuk menampung gambar produk
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 290, 120, 120))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.label_25 = QtWidgets.QLabel(self.frame_2)
        self.label_25.setGeometry(QtCore.QRect(20, 20, 81, 91))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/OneDrive/Documents/SEMESTER 4/GUI/TUBES/UAS/teh_pucuk-removebg-preview.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(20, 60, 120, 120))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(-50, 0, 211, 121))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/12342-coca-cola-wwwcocacolacoid-removebg-preview.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(320, 60, 120, 120))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.label_23 = QtWidgets.QLabel(self.frame_4)
        self.label_23.setGeometry(QtCore.QRect(0, 10, 111, 111))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/fanta_fanta-strawberry-can--330-ml-_full03-removebg-preview.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(170, 60, 120, 120))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.label_22 = QtWidgets.QLabel(self.frame_5)
        self.label_22.setGeometry(QtCore.QRect(-10, 0, 141, 131))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/sprite_sprite-slim-250ml_full01-removebg-preview.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(620, 290, 120, 120))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.label_29 = QtWidgets.QLabel(self.frame_6)
        self.label_29.setGeometry(QtCore.QRect(10, 30, 91, 81))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/tmp_phpdq7gal_10277582_1531703952-removebg-preview.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(470, 60, 120, 120))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.label_21 = QtWidgets.QLabel(self.frame_8)
        self.label_21.setGeometry(QtCore.QRect(-10, 0, 131, 131))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/79355b2a060ec51b51a16047217b17b8-removebg-preview.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(620, 60, 120, 120))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.label_24 = QtWidgets.QLabel(self.frame_7)
        self.label_24.setGeometry(QtCore.QRect(-10, 0, 131, 121))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/big_cola-removebg-preview.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(470, 290, 120, 120))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.label_28 = QtWidgets.QLabel(self.frame_9)
        self.label_28.setGeometry(QtCore.QRect(-10, 0, 141, 131))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/NU-GREEN-TEA-HONEY-450ML-1-scaled-removebg-preview.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setGeometry(QtCore.QRect(170, 290, 120, 120))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.label_27 = QtWidgets.QLabel(self.frame_11)
        self.label_27.setGeometry(QtCore.QRect(10, -10, 101, 151))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/20060207_1-removebg-preview.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setGeometry(QtCore.QRect(320, 290, 120, 120))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setObjectName("frame_10")
        self.label_26 = QtWidgets.QLabel(self.frame_10)
        self.label_26.setGeometry(QtCore.QRect(0, 10, 121, 111))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/a928dac56509f454c075936ce1e4f6b6-removebg-preview.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(20, 240, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setGeometry(QtCore.QRect(610, 530, 120, 120))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setObjectName("frame_12")
        self.label_33 = QtWidgets.QLabel(self.frame_12)
        self.label_33.setGeometry(QtCore.QRect(10, 10, 101, 101))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/lemon_water-removebg-preview.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setGeometry(QtCore.QRect(160, 530, 120, 120))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setObjectName("frame_13")
        self.label_32 = QtWidgets.QLabel(self.frame_13)
        self.label_32.setGeometry(QtCore.QRect(10, 10, 91, 101))
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/isoplus-removebg-preview.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(160, 660, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(610, 660, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setGeometry(QtCore.QRect(310, 530, 120, 120))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_14.setObjectName("frame_14")
        self.label_31 = QtWidgets.QLabel(self.frame_14)
        self.label_31.setGeometry(QtCore.QRect(10, -10, 101, 141))
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/mizone-removebg-preview.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(10, 480, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setGeometry(QtCore.QRect(460, 530, 120, 120))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_15.setObjectName("frame_15")
        self.label_34 = QtWidgets.QLabel(self.frame_15)
        self.label_34.setGeometry(QtCore.QRect(10, 10, 101, 111))
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/yuzu-removebg-preview.png"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.frame_16 = QtWidgets.QFrame(self.frame)
        self.frame_16.setGeometry(QtCore.QRect(10, 530, 120, 120))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_16.setObjectName("frame_16")
        self.label_30 = QtWidgets.QLabel(self.frame_16)
        self.label_30.setGeometry(QtCore.QRect(0, 0, 121, 121))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("C:/Users/LENOVO/Downloads/pocari-removebg-preview.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(460, 660, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(10, 660, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(310, 660, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")

        # Membuat pushButton untuk memilih produk
        self.pushButton_cola = QtWidgets.QPushButton(self.frame)
        self.pushButton_cola.setGeometry(QtCore.QRect(24, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_cola.setFont(font)
        self.pushButton_cola.setDefault(False)
        self.pushButton_cola.setFlat(True)
        self.pushButton_cola.setObjectName("pushButton")

        self.pushButton_sprite = QtWidgets.QPushButton(self.frame)
        self.pushButton_sprite.setGeometry(QtCore.QRect(170, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_sprite.setFont(font)
        self.pushButton_sprite.setDefault(False)
        self.pushButton_sprite.setFlat(True)
        self.pushButton_sprite.setObjectName("pushButton_2")

        self.pushButton_fanstraw = QtWidgets.QPushButton(self.frame)
        self.pushButton_fanstraw.setGeometry(QtCore.QRect(310, 190, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_fanstraw.setFont(font)
        self.pushButton_fanstraw.setDefault(False)
        self.pushButton_fanstraw.setFlat(True)
        self.pushButton_fanstraw.setObjectName("pushButton_3")

        self.pushButton_bigcola = QtWidgets.QPushButton(self.frame)
        self.pushButton_bigcola.setGeometry(QtCore.QRect(620, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_bigcola.setFont(font)
        self.pushButton_bigcola.setDefault(False)
        self.pushButton_bigcola.setFlat(True)
        self.pushButton_bigcola.setObjectName("pushButton_4")

        self.pushButton_fanoren = QtWidgets.QPushButton(self.frame)
        self.pushButton_fanoren.setGeometry(QtCore.QRect(470, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_fanoren.setFont(font)
        self.pushButton_fanoren.setDefault(False)
        self.pushButton_fanoren.setFlat(True)
        self.pushButton_fanoren.setObjectName("pushButton_5")
        
        self.pushButton_tehpucuk = QtWidgets.QPushButton(self.frame)
        self.pushButton_tehpucuk.setGeometry(QtCore.QRect(20, 420, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_tehpucuk.setFont(font)
        self.pushButton_tehpucuk.setDefault(False)
        self.pushButton_tehpucuk.setFlat(True)
        self.pushButton_tehpucuk.setObjectName("pushButton_6")

        self.pushButton_ichi = QtWidgets.QPushButton(self.frame)
        self.pushButton_ichi.setGeometry(QtCore.QRect(180, 420, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ichi.setFont(font)
        self.pushButton_ichi.setDefault(False)
        self.pushButton_ichi.setFlat(True)
        self.pushButton_ichi.setObjectName("pushButton_7")

        self.pushButton_nugreen = QtWidgets.QPushButton(self.frame)
        self.pushButton_nugreen.setGeometry(QtCore.QRect(330, 420, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_nugreen.setFont(font)
        self.pushButton_nugreen.setDefault(False)
        self.pushButton_nugreen.setFlat(True)
        self.pushButton_nugreen.setObjectName("pushButton_8")

        self.pushButton_nuhoney = QtWidgets.QPushButton(self.frame)
        self.pushButton_nuhoney.setGeometry(QtCore.QRect(460, 420, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_nuhoney.setFont(font)
        self.pushButton_nuhoney.setDefault(False)
        self.pushButton_nuhoney.setFlat(True)
        self.pushButton_nuhoney.setObjectName("pushButton_9")

        self.pushButton_fruit = QtWidgets.QPushButton(self.frame)
        self.pushButton_fruit.setGeometry(QtCore.QRect(630, 420, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_fruit.setFont(font)
        self.pushButton_fruit.setDefault(False)
        self.pushButton_fruit.setFlat(True)
        self.pushButton_fruit.setObjectName("pushButton_10")

        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        self.menuMENU = QtWidgets.QMenu(self.menubar)
        self.menuMENU.setObjectName("menuMENU")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMENU.menuAction())

        # Memanggil fungsi retranslateUi
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Fungsi untuk memberi nama/text pada objek
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SELAMAT DATANG"))
        self.label_2.setText(_translate("MainWindow", "MINUMAN BERSODA"))
        self.label_8.setText(_translate("MainWindow", "TEH MENYEGARKAN"))
        self.label_14.setText(_translate("MainWindow", "Isoplus"))
        self.label_15.setText(_translate("MainWindow", "Lemon Water"))
        self.label_16.setText(_translate("MainWindow", "MINUMAN ISOTONIK"))
        self.label_17.setText(_translate("MainWindow", "Yuzu"))
        self.label_18.setText(_translate("MainWindow", "Pocari Sweat"))
        self.label_19.setText(_translate("MainWindow", "Mizone"))
        self.pushButton_cola.setText(_translate("MainWindow", "Coca Cola"))
        self.pushButton_sprite.setText(_translate("MainWindow", "Sprite"))
        self.pushButton_fanstraw.setText(_translate("MainWindow", "Fanta Strawberry"))
        self.pushButton_bigcola.setText(_translate("MainWindow", "Big Cola"))
        self.pushButton_fanoren.setText(_translate("MainWindow", "Fanta Orange"))
        self.pushButton_tehpucuk.setText(_translate("MainWindow", "Teh Pucuk"))
        self.pushButton_ichi.setText(_translate("MainWindow", "Ichi Ocha"))
        self.pushButton_nugreen.setText(_translate("MainWindow", "NU Green Tea"))
        self.pushButton_nuhoney.setText(_translate("MainWindow", "Green Tea Honey"))
        self.pushButton_fruit.setText(_translate("MainWindow", "Fruit Tea Apel"))
        self.menuMENU.setTitle(_translate("MainWindow", "MENU"))
        
        # Mengkoneksikan pushbotton teh pucuk dengan fungsi pucuk
        self.pushButton_tehpucuk.clicked.connect(self.pucuk)
    
    # Fungsi untuk pindah ke halaman produk
    def pucuk(self):
        DETAILPRODUK.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    MainWindow = QtWidgets.QMainWindow()
    ui = menufix()
    ui.setupUi(MainWindow)

    DETAILPRODUK= QtWidgets.QMainWindow()
    detaiWindow = detail_produk()
    detaiWindow.setupUi(DETAILPRODUK)   

    MainWindow.show()
    sys.exit(app.exec_())

